### ISSUE TITLE
node_modules folder size

### ISSUE THREAD

**Issue by OziOcb** [tareq1988/vue-wp-starter#11]
After running 'npm install' an entire node_modules folder is beeing created (160MB). That makes my plugin folder huge compering to other plugins.
What's the best solution for that?

**Comment by tripflex** [comment]
@OziOcb when you build for release you should absolutely make sure in your build process to exclude those files, `node_modules` is only needed for development, plus you will probably only want to release the built vue files, not the source files as well.

I haven't dug into building from this repo but you will probably need to come up with a build solution to only include needed files

**Comment by OziOcb** [comment]
Hi and thanks for your reply.

I know that entire node_modules folder should stay but what confused me were Running and Post Installation sections from the README file.

https://github.com/tareq1988/vue-wp-starter#-running

According to them, I should clone this repo into WP's plugins folder and run 'npm install' init. This way, I ended up having an entire plugin project inside this plugin folder, which did not make any sense.

I should probably emphasise that I have a minimal WordPress experience, especially in the area of building plugins (I needed this repo for a quick, job-related task).

**Comment by tareq1988** [comment]
`node_modules` folder is for development purpose only. As @tripflex mentioned, you should exclude that folder when you are distributing the plugin.
