### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by typerory** [tareq1988/vue-wp-starter#4]
First of all, THANK YOU. This is exactly what a vue/js developer that knows absolutely nothing about PHP needs to get a WordPress plugin installed.

So to test, I downloaded the plugin and installed it. I see the admin menu. I add "[vue-app]" on a page but I'm not seeing the 'Welcome to Your Vue.js Frontend App' message coming from {msg}. What am I doing wrong? LOL.

**Comment by SketchBookkeeper** [comment]
I'm just finding this repo myself, super awesome starter kit. So did you add the [vue-app] shortcode to the wysiwyg of a post or page? if you use the shortcode outside of a post's content, you will need to use `echo do_shortcode('[vue-app]')` to call the shortcode.

[Learn more about shortcodes here](https://developer.wordpress.org/reference/functions/do_shortcode/)

**Comment by typerory** [comment]
Yes. Strange. Here it is: https://imgur.com/gallery/thQwhCG

**Comment by tareq1988** [comment]
Did you change scripts handle in `class-assets.php`? In that case you have to change those also in the `class-frontend.php`. Make sure the JS files are loading correctly in the frontend.

**Comment by typerory** [comment]
I didn't change anything yet. I'm getting 200 on frontend.js. I disabled all the plugins. I flushed all cache. My only guess is that the Divi theme is interfering with it? I was able to get a Vue code block going yesterday and I've also used shortcodes with Divi. I'm out of ideas.

**Comment by typerory** [comment]
I just tried it with a fresh install and the 2015 theme. Same thing. Now I'm thinking it's a Site Ground hosting setting?

**Comment by typerory** [comment]
Try it: https://demo.rokable.com/wp-admin
u: admin@demo.rokable.com
p: admin@demo.rokable.com

**Comment by tareq1988** [comment]
Seems like it was a build issue. The JS file build wasn't updated. 

Pushed the new JS scripts, also added `npm run dev-build` command to generate development build as `npm run build` generates minified JS scripts. Download and installing it again should solve the issue.

**Comment by typerory** [comment]
You nailed it! This is soooo sweet.
